<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Reward extends Model
{
    protected $fillable = [
        'member_id',
        'reward_type',
        'content',
        'memo',
        'is_auto_generated',
        'usable_date'
    ];

    protected $casts = [
        'is_auto_generated' => 'boolean',
        'created_at' => 'datetime',
        'usable_date' => 'date'
    ];

    // 리워드 타입 상수 정의
    const REWARD_TYPES = [
        '연차추가',
        '반차추가',
        '네시퇴근 추가',
        '연차차감',
        '반차차감',
        '재택근무 제외',
        '업무재배치',
        '경위서 작성',
        '징계절차 개시'
    ];

    /**
     * 리워드 타입 목록을 반환합니다.
     */
    public static function getRewardTypes(): array
    {
        return self::REWARD_TYPES;
    }

    /**
     * 이 리워드와 연관된 멤버를 가져옵니다.
     */
    public function member(): BelongsTo
    {
        return $this->belongsTo(Member::class);
    }

    /**
     * 자동 생성된 리워드인지 확인합니다.
     */
    public function isAutoGenerated(): bool
    {
        return $this->is_auto_generated;
    }
}
